library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- axi_lite library provided by hdl-modules (fetched via Bender).
-- See: https://github.com/hdl-modules/hdl-modules
library axi_lite;
use axi_lite.axi_lite_pkg.all;

library work;
use work.<<NAME>>_pkg.all;
-- Generated packages (run `make regs` to produce these):
use work.<<NAME>>_regs_pkg.all;
use work.<<NAME>>_register_record_pkg.all;

-- <<NAME>> top-level.
--
-- Integrates the AXI4-Lite register block (generated by hdl_registers)
-- with the <<NAME>>_core logic. All register decoding is handled by the
-- generated entity; this wrapper wires decoded register values to the
-- core and maps status values back to the register block.
--
-- AXI4-Lite address width: 8 bits (covers up to 64 word-aligned registers).
entity <<NAME>>_top is
    port (
        -- System clock, rising-edge triggered.
        clk           : in  std_logic;
        -- Synchronous active-low reset.
        rst_n         : in  std_logic;

        -- ── Design I/O ───────────────────────────────────────────────────────
        -- Pulse input to be counted by <<NAME>>_core.
        pulse_i       : in  std_logic;

        -- ── AXI4-Lite subordinate register interface ─────────────────────────
        s_axi_m2s     : in  axi_lite_m2s_t;
        s_axi_s2m     : out axi_lite_s2m_t
    );
end entity <<NAME>>_top;

architecture rtl of <<NAME>>_top is

    -- Register record signals connecting the generated register file to the core.
    -- regs_down: register values written by the host (conf, command registers).
    -- regs_up:   status values driven by the core (status register).
    signal regs_down : <<NAME>>_regs_down_t := <<NAME>>_regs_down_init;
    signal regs_up   : <<NAME>>_regs_up_t   := <<NAME>>_regs_up_init;

    -- Bridging signals for register fields whose VHDL record type (unsigned)
    -- doesn't directly match a plain std_logic_vector core port -- content
    -- generated by `make regs`, do not hand-edit.
    -- BEGIN AUTOGEN REGISTER SIGNALS
    signal pulse_count : std_logic_vector(16 - 1 downto 0);
    -- END AUTOGEN REGISTER SIGNALS

begin

    -- u_regs: Generated AXI4-Lite register file.
    --
    -- Entity and packages are produced by `make regs` via hdl_registers.
    -- Source: out/regs/vhdl/<<NAME>>_register_file_axi_lite.vhd
    u_regs : entity work.<<NAME>>_register_file_axi_lite
        port map (
            clk          => clk,
            reset        => not rst_n,      -- generated entity uses active-high reset
            axi_lite_m2s => s_axi_m2s,
            axi_lite_s2m => s_axi_s2m,
            regs_up      => regs_up,
            regs_down    => regs_down
        );

    -- u_core: Counter core logic, and its register wiring.
    --
    -- Content between the markers is generated by `make regs` -- do not
    -- hand-edit; edit regs/<<NAME>>_regs.toml instead. Everything else in
    -- this file (ports, u_regs above) is yours to edit freely.
    -- BEGIN AUTOGEN REGISTERS
    regs_up.status.pulse_count <= unsigned(pulse_count);

    u_core : entity work.<<NAME>>_core
        port map (
            clk => clk,
            rst_n => rst_n,
            enable_i => regs_down.conf.enable,
            increment_i => regs_down.conf.increment,
            reset_count_i => regs_down.command.reset_count,
            enabled_o => regs_up.status.enabled,
            pulse_count_o => pulse_count
        );
    -- END AUTOGEN REGISTERS

end architecture rtl;
