-- uart_top.vhd
--
-- Top-level wrapper for the UART module.
--
-- Integrates the AXI4-Lite register block (generated by hdl_registers from
-- regs/uart_regs.toml) with uart_core, and exposes:
--   • physical UART serial pins (uart_tx_o, uart_rx_i)
--   • AXI4-Stream TX slave  (s_axis_*)  — bytes to transmit
--   • AXI4-Stream RX master (m_axis_*)  — received bytes
--   • AXI4-Lite subordinate (s_axi_*)   — register access
--
-- ── Register map ──────────────────────────────────────────────────────────────
--
-- Register definitions are in regs/uart_regs.toml.  Run `make regs` to
-- regenerate the VHDL packages, C header, and HTML documentation.
--
-- ctrl  (offset 0x00, RW)
-- .. wavedrom::
--
--    { "reg": [
--      { "bits": 1,  "name": "tx_enable", "attr": ["RW", "def 0"],
--        "description": "Enable TX serialiser. Deassert to hold TX line idle." },
--      { "bits": 1,  "name": "rx_enable", "attr": ["RW", "def 0"],
--        "description": "Enable RX deserialiser. Deassert to ignore incoming data." },
--      { "bits": 1,  "name": "loopback",  "attr": ["RW", "def 0"],
--        "description": "Connect TX output internally to RX input for self-test." },
--      { "bits": 29, "name": "(reserved)", "attr": "RO" }
--    ], "config": { "hspace": 700, "bits": 32, "lanes": 1 } }
--
-- baud_div  (offset 0x04, RW)
-- .. wavedrom::
--
--    { "reg": [
--      { "bits": 16, "name": "divisor",    "attr": ["RW", "def 868"],
--        "description": "Baud rate divisor: baud_rate = clk_freq / divisor. Min 2. Example: 868 = 115200 baud at 100 MHz." },
--      { "bits": 16, "name": "(reserved)", "attr": "RO" }
--    ], "config": { "hspace": 700, "bits": 32, "lanes": 1 } }
--
-- status  (offset 0x08, RO)
-- .. wavedrom::
--
--    { "reg": [
--      { "bits": 1,  "name": "tx_busy",       "attr": "RO",
--        "description": "Asserted while TX is serialising a frame." },
--      { "bits": 1,  "name": "rx_frame_error", "attr": "RO",
--        "description": "Pulsed for one clock when a bad stop bit is detected." },
--      { "bits": 1,  "name": "rx_overflow",    "attr": "RO",
--        "description": "Pulsed for one clock when an RX byte is lost (buffer full)." },
--      { "bits": 29, "name": "(reserved)",     "attr": "RO" }
--    ], "config": { "hspace": 700, "bits": 32, "lanes": 1 } }
--
-- ── AXI4-Lite address map ─────────────────────────────────────────────────────
--
-- Address width: 8 bits (covers up to 64 word-aligned registers).
-- All registers are 32-bit word aligned; upper bits of each register are
-- reserved and read as zero.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- axi_lite library provided by hdl-modules (fetched via `make deps`).
-- Source: deps/hdl_modules
library axi_lite;
use axi_lite.axi_lite_pkg.all;

library work;
use work.uart_pkg.all;
-- Generated packages — produced by `make regs` from regs/uart_regs.toml:
use work.uart_regs_regs_pkg.all;
use work.uart_regs_register_record_pkg.all;

entity uart_top is
    port (
        -- System clock, rising-edge triggered.
        clk           : in  std_logic;
        -- Synchronous active-low reset. Clears all internal state.
        rst_n         : in  std_logic;

        -- ── Physical UART pins ────────────────────────────────────────────────
        -- UART serial output.  Idle-high.
        uart_tx_o     : out std_logic;
        -- UART serial input.  Idle-high.
        uart_rx_i     : in  std_logic;

        -- ── AXI4-Stream TX slave (bytes to transmit) ──────────────────────────
        -- 8-bit data byte. Hold stable while tvalid is asserted.
        s_axis_tdata  : in  std_logic_vector(C_DATA_W-1 downto 0);
        -- Assert when tdata holds a valid byte to transmit.
        s_axis_tvalid : in  std_logic;
        -- Pulsed for one clock cycle when the byte is accepted by the serialiser.
        s_axis_tready : out std_logic;
        -- End-of-packet. Accepted for AXI4-Stream compliance; no effect on 8N1.
        s_axis_tlast  : in  std_logic;

        -- ── AXI4-Stream RX master (received bytes) ────────────────────────────
        -- 8-bit received byte. Stable while tvalid is asserted.
        m_axis_tdata  : out std_logic_vector(C_DATA_W-1 downto 0);
        -- Asserted when tdata contains a valid received byte. Held until tready.
        m_axis_tvalid : out std_logic;
        -- Assert to consume tdata and deassert tvalid.
        m_axis_tready : in  std_logic;
        -- Always '1' alongside tvalid: every UART byte is an independent packet.
        m_axis_tlast  : out std_logic;

        -- ── AXI4-Lite subordinate register interface ──────────────────────────
        -- Master-to-slave channel: write address, write data, read address.
        s_axi_m2s     : in  axi_lite_m2s_t;
        -- Slave-to-master channel: write response, read data.
        s_axi_s2m     : out axi_lite_s2m_t
    );
end entity uart_top      ;

architecture rtl of uart_top is

    -- Register records produced by the generated register file.
    -- regs_down: fields written by the AXI4-Lite host (ctrl, baud_div).
    -- regs_up:   fields driven by uart_core back to the host (status).
    signal regs_down : uart_regs_regs_down_t := uart_regs_regs_down_init;
    signal regs_up   : uart_regs_regs_up_t   := uart_regs_regs_up_init;

begin

    -- u_regs: AXI4-Lite register file (generated by `make regs`).
    --
    -- Source: gen/vhdl/uart_regs_register_file_axi_lite.vhd
    -- Decodes AXI4-Lite read/write transactions and presents field values as
    -- typed VHDL record signals.  The generated entity uses an active-high reset.
    u_regs : entity work.uart_regs_register_file_axi_lite
        port map (
            clk          => clk,
            reset        => not rst_n,      -- generated entity uses active-high reset
            axi_lite_m2s => s_axi_m2s,
            axi_lite_s2m => s_axi_s2m,
            regs_up      => regs_up,
            regs_down    => regs_down
        );

    -- u_core: UART TX/RX core (uart_core → uart_tx + uart_rx).
    --
    -- Register fields from regs_down are forwarded to the TX and RX sub-modules.
    -- Status signals from the core are written back into regs_up so they appear
    -- as readable register fields on the AXI4-Lite bus.
    u_core : entity work.uart_core
        port map (
            clk            => clk,
            rst_n          => rst_n,
            -- ctrl register → TX/RX enable and loopback
            tx_enable_i    => regs_down.ctrl.tx_enable,
            rx_enable_i    => regs_down.ctrl.rx_enable,
            loopback_i     => regs_down.ctrl.loopback,
            -- baud_div register → shared baud divisor
            baud_div_i     => regs_down.baud_div.divisor,
            -- status register fields ← core
            tx_busy_o      => regs_up.status.tx_busy,
            rx_frame_err_o => regs_up.status.rx_frame_error,
            rx_overflow_o  => regs_up.status.rx_overflow,
            -- AXI4-Stream TX
            s_axis_tdata   => s_axis_tdata,
            s_axis_tvalid  => s_axis_tvalid,
            s_axis_tready  => s_axis_tready,
            s_axis_tlast   => s_axis_tlast,
            -- AXI4-Stream RX
            m_axis_tdata   => m_axis_tdata,
            m_axis_tvalid  => m_axis_tvalid,
            m_axis_tready  => m_axis_tready,
            m_axis_tlast   => m_axis_tlast,
            -- Physical UART pins
            uart_tx_o      => uart_tx_o,
            uart_rx_i      => uart_rx_i
        );

end architecture rtl;
