#!/usr/bin/env bash
# gen_filelist.sh — Generate filelist.f from Bender for hdl_autodoc.
#
# Usage (called by the Makefile):
#   bash scripts/gen_filelist.sh > filelist.f
#
# Outputs VHDL source paths in compilation order (leaves first).
# The hdl_autodoc parse_hierarchy.py script reads this file to discover modules.
#
# Bender is used when available and its dependencies have been fetched
# (i.e. after `make deps`).  When Bender fails or produces no VHDL paths,
# the script falls back to listing project source files directly in the
# correct compilation order.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BENDER="${BENDER:-bender}"

echo "# filelist.f — generated by scripts/gen_filelist.sh"
echo "# Do not edit manually; re-run: make filelist"
echo ""

# ── Helper: try Bender for a target, emit output only if it contains .vhd/.sv ──
bender_flist() {
    local target="$1"
    local output
    output=$("$BENDER" script flist -t "$target" --no-default-target 2>/dev/null) || true
    if echo "$output" | grep -qE '\.(vhd|sv|v)$'; then
        echo "$output"
        return 0
    fi
    return 1
}

# ── VHDL RTL sources ──────────────────────────────────────────────────────────
if ! bender_flist rtl_vhdl; then
    echo "# (Bender unavailable or deps not fetched — using direct file list)"
    echo ""
    # Generated register packages (emit if out/regs/vhdl exists and has files)
    if [ -d "$REPO_ROOT/out/regs/vhdl" ]; then
        for f in "$REPO_ROOT"/out/regs/vhdl/*.vhd; do
            [ -f "$f" ] && echo "$f"
        done
    fi
    # Project VHDL sources in compilation order (package → core → top).
    # Add your project's files here after running `make init NAME=<project>`.
    for f in "$REPO_ROOT"/src/vhdl/<<NAME>>_pkg.vhd \
              "$REPO_ROOT"/src/vhdl/<<NAME>>_core.vhd \
              "$REPO_ROOT"/src/vhdl/<<NAME>>_top.vhd; do
        [ -f "$f" ] && echo "$f"
    done
fi

# SystemVerilog sources are intentionally excluded from the doc filelist.
# Including them causes parse_hierarchy.py to see duplicate module names and
# resolve <<NAME>>_core to the SV file, which breaks sphinx-vhdl and the
# ghdl-yosys-plugin schematic pipeline.  SV files are alternate simulation
# targets, not doc targets.
