#!/usr/bin/env python3
"""gen_verible_filelist.py — Generate verible.filelist for the Verible Language Server.

Queries Bender for the SystemVerilog RTL file list and writes verible.filelist
in the repository root.  The server searches upward from the project root to
find this file, enabling cross-file features (go-to-definition, find-references,
rename) across the whole project.

Usage:
  make verible-ls
  python scripts/gen_verible_filelist.py
"""

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "verible.filelist"


def run_bender(*args: str) -> list[str]:
    """Run a bender command from the repo root; return non-empty output lines."""
    result = subprocess.run(
        ["bender", *args],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    if result.returncode != 0:
        print(f"  bender {' '.join(args)}: {result.stderr.strip()}", file=sys.stderr)
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def bender_flist(*targets: str) -> list[Path]:
    """Return existing SV files for the given Bender targets, relative to REPO_ROOT."""
    target_flags: list[str] = []
    for t in targets:
        target_flags += ["-t", t]
    lines = run_bender("script", "flist", *target_flags, "--no-default-target")
    paths: list[Path] = []
    for line in lines:
        p = Path(line)
        if not p.is_absolute():
            p = REPO_ROOT / p
        rel = p.resolve().relative_to(REPO_ROOT)
        if p.exists():
            paths.append(rel)
        else:
            print(f"  skipping (not found): {rel}", file=sys.stderr)
    return paths


def main() -> None:
    print("Generating verible.filelist...")

    files = bender_flist("rtl_sv")

    if not files:
        print(
            "  WARNING: no SV files found — run 'make deps' first or check Bender.yml",
            file=sys.stderr,
        )

    with OUTPUT.open("w") as f:
        f.write("# verible.filelist — Verible Language Server project file list\n")
        f.write("# Generated by scripts/gen_verible_filelist.py — do not hand-edit.\n")
        f.write("# Regenerate with: make verible-ls\n")
        for path in files:
            f.write(f"{path.as_posix()}\n")

    print(f"Written: verible.filelist ({len(files)} file(s))")
    for path in files:
        print(f"  {path}")


if __name__ == "__main__":
    main()
