#!/usr/bin/env python3
"""gen_vhdl_ls.py — Generate vhdl_ls.toml for the VHDL Language Server.

Queries Bender for VHDL file lists and maps them to VHDL library names,
then writes vhdl_ls.toml in the repository root.

Library mapping:
  axi_lite      ← hdl_modules/modules/axi_lite/
  register_file ← hdl_modules/modules/register_file/
  work          ← rtl_vhdl + gen_vhdl (project RTL + generated register files)
  tb_lib        ← tb_vhdl (VUnit testbench, simulation target)

Usage:
  make vhdl-ls
  python scripts/gen_vhdl_ls.py
"""

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# hdl-modules files that must be compiled into named libraries.
# Mirrors the VHDL_AXI_LITE / VHDL_REG_FILE variables in the Makefile.
HDL_MODULES_LIBS: dict[str, list[str]] = {
    "axi_lite": [
        "modules/axi_lite/src/axi_lite_pkg.vhd",
    ],
    "register_file": [
        "modules/register_file/src/register_file_pkg.vhd",
        "modules/register_file/src/axi_lite_register_file.vhd",
    ],
}


def run_bender(*args: str) -> list[str]:
    """Run a bender command from the repo root; return non-empty output lines."""
    result = subprocess.run(
        ["bender", *args],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    if result.returncode != 0:
        print(f"  bender {' '.join(args)}: {result.stderr.strip()}", file=sys.stderr)
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def bender_flist(*targets: str) -> list[Path]:
    """Return existing files for the given Bender targets, relative to REPO_ROOT."""
    target_flags: list[str] = []
    for t in targets:
        target_flags += ["-t", t]
    lines = run_bender("script", "flist", *target_flags, "--no-default-target")
    paths: list[Path] = []
    for line in lines:
        p = Path(line)
        if not p.is_absolute():
            p = REPO_ROOT / p
        rel = p.resolve().relative_to(REPO_ROOT)
        if p.exists():
            paths.append(rel)
        else:
            print(f"  skipping (not yet generated): {rel}", file=sys.stderr)
    return paths


def write_toml(libraries: dict[str, list[Path]], output: Path) -> None:
    with output.open("w") as f:
        f.write("# vhdl_ls.toml — VHDL Language Server configuration\n")
        f.write("# Generated by scripts/gen_vhdl_ls.py — do not hand-edit.\n")
        f.write("# Regenerate with: make vhdl-ls\n")
        for lib_name, files in libraries.items():
            if not files:
                continue
            f.write(f"\n[libraries.{lib_name}]\n")
            f.write("files = [\n")
            for path in files:
                f.write(f'  "{path.as_posix()}",\n')
            f.write("]\n")


def main() -> None:
    print("Generating vhdl_ls.toml...")

    libraries: dict[str, list[Path]] = {}

    # ── hdl-modules dependency libraries ──────────────────────────────────────
    hdl_path_lines = run_bender("path", "hdl_modules")
    if hdl_path_lines:
        hdl_root = Path(hdl_path_lines[0])
        for lib_name, rel_files in HDL_MODULES_LIBS.items():
            files: list[Path] = []
            for rel in rel_files:
                p = (hdl_root / rel).resolve()
                if p.exists():
                    files.append(p.relative_to(REPO_ROOT))
                else:
                    print(f"  skipping (not found): {p}", file=sys.stderr)
            libraries[lib_name] = files
    else:
        print("  WARNING: hdl_modules not found — run 'make deps' first", file=sys.stderr)

    # ── Project RTL + generated register files → work ─────────────────────────
    libraries["work"] = bender_flist("rtl_vhdl") + bender_flist("gen_vhdl")

    # ── VUnit testbench → tb_lib ──────────────────────────────────────────────
    tb_files = bender_flist("simulation", "tb_vhdl")
    if tb_files:
        libraries["tb_lib"] = tb_files

    # ── Write output ──────────────────────────────────────────────────────────
    output = REPO_ROOT / "vhdl_ls.toml"
    write_toml(libraries, output)

    print(f"Written: vhdl_ls.toml")
    for lib_name, files in libraries.items():
        if files:
            print(f"  [{lib_name}]: {len(files)} file(s)")


if __name__ == "__main__":
    main()
