#!/usr/bin/env bash
# gen_filelist.sh — Generate filelist.f from Bender for hdl_autodoc.
#
# Usage (called by the Makefile):
#   bash scripts/gen_filelist.sh > filelist.f
#
# Outputs VHDL source paths in compilation order (leaves first).
# The hdl_autodoc parse_hierarchy.py script reads this file to discover modules.
#
# Bender is used when available and its dependencies have been fetched
# (i.e. after `make deps`).  When Bender fails or produces no VHDL paths,
# the script falls back to listing project source files directly in the
# correct compilation order.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BENDER="${BENDER:-bender}"

echo "# filelist.f — generated by scripts/gen_filelist.sh"
echo "# Do not edit manually; re-run: make filelist"
echo ""

# ── Helper: try Bender for a target, emit output only if its files really
# exist on disk. Bender.yml declares both rtl_vhdl and rtl_sv (and gen_vhdl/
# gen_sv) file lists unconditionally -- it describes the template's full
# dual-language capability and isn't pruned by `make init`, which only
# flattens src/ for the chosen language. So `bender script flist -t
# rtl_vhdl` "succeeds" (emits .vhd-suffixed paths matching the expected
# extension) even for a post-init SV-only project, where those exact files
# were deleted -- checking the output string's extension alone isn't
# enough to tell the two states apart, only checking the files themselves
# actually exist does.
bender_flist() {
    local target="$1"
    local output
    output=$("$BENDER" script flist -t "$target" --no-default-target 2>/dev/null) || true
    if [ -z "$output" ]; then
        return 1
    fi
    local f
    while IFS= read -r f; do
        [ -f "$f" ] || return 1
    done <<< "$output"
    echo "$output"
    return 0
}

# ── VHDL RTL sources ──────────────────────────────────────────────────────────
# Tried first: pre-init, src/vhdl/<<NAME>>_*.vhd exist as real files on disk
# (the <<NAME>> placeholder is just a filename component, not evidence the
# file is missing), so this branch always wins pre-init regardless of which
# language the project will end up using — matching every other CI job's
# documented pre-init limitation. Post-init, this correctly finds nothing
# for an SV-only project (src/vhdl/ was deleted by `make init`), falling
# through to the SV branch below. The two branches are mutually exclusive
# in every real state this script runs in (pre-init: only src/vhdl/ and
# src/sv/ placeholder files exist, never a genuine single-language project;
# post-init: only one of src/vhdl/ or src/sv/ survives `make init`'s
# flattening), so there is no real risk of both matching for the same
# project and producing the "duplicate module name" collision an earlier
# version of this script blanket-avoided by excluding SV entirely.
if bender_flist rtl_vhdl; then
    # Generated register packages must also be listed so parse_hierarchy.py
    # can resolve entities instantiated from <<NAME>>_top (e.g.
    # <<NAME>>_register_file_axi_lite) — otherwise it KeyErrors on a child
    # module it never saw. Emitted only if `make regs` has already run.
    bender_flist gen_vhdl || true
elif bender_flist rtl_sv; then
    # Same reasoning as gen_vhdl above, for the SV-generated register file.
    bender_flist gen_sv || true
else
    echo "# (Bender unavailable or deps not fetched — using direct file list)"
    echo ""
    # Generated register packages (emit if out/regs/vhdl exists and has files)
    if [ -d "$REPO_ROOT/out/regs/vhdl" ]; then
        for f in "$REPO_ROOT"/out/regs/vhdl/*.vhd; do
            [ -f "$f" ] && echo "$f"
        done
    fi
    # Project VHDL sources in compilation order (package → core → top).
    # Add your project's files here after running `make init NAME=<project>`.
    for f in "$REPO_ROOT"/src/vhdl/<<NAME>>_pkg.vhd \
              "$REPO_ROOT"/src/vhdl/<<NAME>>_core.vhd \
              "$REPO_ROOT"/src/vhdl/<<NAME>>_top.vhd; do
        [ -f "$f" ] && echo "$f"
    done
    # Generated register packages (emit if out/regs/sv exists and has files)
    if [ -d "$REPO_ROOT/out/regs/sv" ]; then
        for f in "$REPO_ROOT"/out/regs/sv/*.sv; do
            [ -f "$f" ] && echo "$f"
        done
    fi
    # Project SV sources in compilation order (package → core → top).
    for f in "$REPO_ROOT"/src/sv/<<NAME>>_pkg.sv \
              "$REPO_ROOT"/src/sv/<<NAME>>_core.sv \
              "$REPO_ROOT"/src/sv/<<NAME>>_top.sv; do
        [ -f "$f" ] && echo "$f"
    done
fi
