#!/usr/bin/env bash
# gen_filelist.sh — Generate filelist.f from Bender for hdl_autodoc.
#
# Usage (called by the Makefile):
#   bash scripts/gen_filelist.sh > filelist.f
#
# Outputs VHDL and SV source paths (dependency-order, leaves first).
# The hdl_autodoc parse_hierarchy.py script reads this file to discover modules.

set -euo pipefail

BENDER="${BENDER:-bender}"

echo "# filelist.f — generated by scripts/gen_filelist.sh"
echo "# Do not edit manually; re-run: make filelist"
echo ""

# VHDL RTL sources (dependency-first: pkg before core, core before top)
$BENDER script flist -t rtl_vhdl --no-default-target 2>/dev/null || true

# SystemVerilog RTL sources
$BENDER script flist -t rtl_sv --no-default-target 2>/dev/null || true
