// <<NAME>> top-level (SystemVerilog).
//
// Integrates <<NAME>>_core with a simple register bus interface.
// Note: the VHDL register block generated by hdl_registers is the primary
// register integration path. This SV top uses a flat AXI4-Lite port list
// and delegates register decoding to the generated VHDL entity when mixed-
// language simulation is required, or to a hand-written SV register block.
//
// For pure SV flows, replace the register port list with your preferred
// register bus protocol.
module <<NAME>>_top (
    // System clock, rising-edge triggered.
    input  logic        clk,
    // Synchronous active-low reset.
    input  logic        rst_n,

    // ── Design I/O ──────────────────────────────────────────────────────────
    // Pulse input to be counted.
    input  logic        pulse_i,

    // ── AXI4-Lite subordinate register interface (32-bit, 8-bit addr) ───────
    input  logic        s_axi_awvalid,
    output logic        s_axi_awready,
    input  logic [7:0]  s_axi_awaddr,
    input  logic        s_axi_wvalid,
    output logic        s_axi_wready,
    input  logic [31:0] s_axi_wdata,
    input  logic [3:0]  s_axi_wstrb,
    output logic        s_axi_bvalid,
    input  logic        s_axi_bready,
    output logic [1:0]  s_axi_bresp,
    input  logic        s_axi_arvalid,
    output logic        s_axi_arready,
    input  logic [7:0]  s_axi_araddr,
    output logic        s_axi_rvalid,
    input  logic        s_axi_rready,
    output logic [31:0] s_axi_rdata,
    output logic [1:0]  s_axi_rresp
);

    // ── Decoded register signals ─────────────────────────────────────────────
    // These are driven by the register block (generated or hand-written).
    logic              enable_r;
    int unsigned       increment_r;
    logic              reset_counter_r;

    // Status signals driven by the core back to the register block.
    logic              enabled_s;
    logic [<<NAME>>_pkg::C_COUNT_W-1:0] pulse_count_s;

    // ── u_core: Counter core ─────────────────────────────────────────────────
    <<NAME>>_core u_core (
        .clk           (clk),
        .rst_n         (rst_n),
        .enable_i      (enable_r),
        .increment_i   (increment_r),
        .reset_count_i (reset_counter_r),
        .enabled_o     (enabled_s),
        .pulse_count_o (pulse_count_s)
    );

    // ── Register block placeholder ───────────────────────────────────────────
    // TODO: Instantiate your register block here to decode the AXI4-Lite bus
    // and drive enable_r, increment_r, reset_counter_r; capture enabled_s and
    // pulse_count_s into the status register.
    //
    // Option A: Use the VHDL-generated entity (mixed-language via GHDL):
    //   <<NAME>>_register_file_axi_lite u_regs ( ... );
    //
    // Option B: Instantiate a hand-written SV register block.

    // Drive AXI outputs low until a register block is instantiated.
    assign s_axi_awready = 1'b0;
    assign s_axi_wready  = 1'b0;
    assign s_axi_bvalid  = 1'b0;
    assign s_axi_bresp   = 2'b00;
    assign s_axi_arready = 1'b0;
    assign s_axi_rvalid  = 1'b0;
    assign s_axi_rdata   = '0;
    assign s_axi_rresp   = 2'b00;

    assign enable_r        = 1'b1;   // stub: always enabled
    assign increment_r     = 1;      // stub: increment by 1
    assign reset_counter_r = 1'b0;   // stub: never reset

endmodule : <<NAME>>_top
