// <<NAME>> top-level (SystemVerilog).
//
// Integrates the AXI4-Lite register file (generated by hdl_registers +
// PeakRDL-regblock) with the <<NAME>>_core logic. All register decoding is
// handled by the generated module; this wrapper wires decoded register
// values to the core and maps status values back to the register file.
module <<NAME>>_top (
    // System clock, rising-edge triggered.
    input  logic        clk,
    // Synchronous active-low reset.
    input  logic        rst_n,

    // ── Design I/O ──────────────────────────────────────────────────────────
    // Pulse input to be counted.
    input  logic        pulse_i,

    // ── AXI4-Lite subordinate register interface (32-bit, 8-bit addr) ───────
    input  logic        s_axi_awvalid,
    output logic        s_axi_awready,
    input  logic [7:0]  s_axi_awaddr,
    input  logic        s_axi_wvalid,
    output logic        s_axi_wready,
    input  logic [31:0] s_axi_wdata,
    input  logic [3:0]  s_axi_wstrb,
    output logic        s_axi_bvalid,
    input  logic        s_axi_bready,
    output logic [1:0]  s_axi_bresp,
    input  logic        s_axi_arvalid,
    output logic        s_axi_arready,
    input  logic [7:0]  s_axi_araddr,
    output logic        s_axi_rvalid,
    input  logic        s_axi_rready,
    output logic [31:0] s_axi_rdata,
    output logic [1:0]  s_axi_rresp
);

    // ── Register file signals ────────────────────────────────────────────────
    // hwif_out: register values written by the host (conf, command registers).
    // hwif_in:  status values driven by the core (status register).
    <<NAME>>_register_file_axi_lite_pkg::<<NAME>>__out_t hwif_out;
    <<NAME>>_register_file_axi_lite_pkg::<<NAME>>__in_t  hwif_in;

    // ── u_regs: Generated AXI4-Lite register file ───────────────────────────
    //
    // Module and package are produced by `make regs` via hdl_registers +
    // PeakRDL-regblock. Source: out/regs/sv/<<NAME>>_register_file_axi_lite.sv
    //
    // Bus-side connection: this project's s_axi_* ports don't match the
    // generated module's flattened s_axil_* names 1:1 (it also has
    // AWPROT/ARPROT, which this port list doesn't expose) -- wired by hand
    // below, not by the generator.
    <<NAME>>_register_file_axi_lite u_regs (
        .clk           (clk),
        .rst           (~rst_n),          // generated module uses active-high reset
        .s_axil_awready(s_axi_awready),
        .s_axil_awvalid(s_axi_awvalid),
        .s_axil_awaddr (s_axi_awaddr),
        .s_axil_awprot (3'b000),
        .s_axil_wready (s_axi_wready),
        .s_axil_wvalid (s_axi_wvalid),
        .s_axil_wdata  (s_axi_wdata),
        .s_axil_wstrb  (s_axi_wstrb),
        .s_axil_bready (s_axi_bready),
        .s_axil_bvalid (s_axi_bvalid),
        .s_axil_bresp  (s_axi_bresp),
        .s_axil_arready(s_axi_arready),
        .s_axil_arvalid(s_axi_arvalid),
        .s_axil_araddr (s_axi_araddr),
        .s_axil_arprot (3'b000),
        .s_axil_rready (s_axi_rready),
        .s_axil_rvalid (s_axi_rvalid),
        .s_axil_rdata  (s_axi_rdata),
        .s_axil_rresp  (s_axi_rresp),
        .hwif_in       (hwif_in),
        .hwif_out      (hwif_out)
    );

    // ── u_core: Counter core logic, and its register wiring ─────────────────
    //
    // Content between the markers is generated by `make regs` -- do not
    // hand-edit; edit regs/<<NAME>>_regs.toml instead. Everything else in
    // this file (ports, u_regs above) is yours to edit freely.
    // BEGIN AUTOGEN REGISTERS
    <<NAME>>_core u_core (
        .clk(clk),
        .rst_n(rst_n),
        .enable_i(hwif_out.conf.enable.value),
        .increment_i(hwif_out.conf.increment.value),
        .reset_count_i(hwif_out.command.reset_count.value),
        .enabled_o(hwif_in.status.enabled.next),
        .pulse_count_o(hwif_in.status.pulse_count.next)
    );
    // END AUTOGEN REGISTERS

endmodule : <<NAME>>_top
